name: pau_sosyal
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  #navigation
  auto_route: ^7.8.4

  #config
  easy_localization: ^3.0.3

  #utility
  easy_logger: ^0.0.2
  google_fonts: ^6.1.0
  kartal: ^3.5.0
  logger: ^2.0.2+1
 
  flutter:
    sdk: flutter
  
  #modules
  gen:
    path: module/gen

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

  flutter_test:
    sdk: flutter
  
  very_good_analysis: ^5.1.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  
flutter_native_splash:
  color: "#ffffff"
  image: assets/app/app_icon.png
  android_12:
    image: assets/app/app_icon.png
    
flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/app/
